version: '3.4'

services:
  softplan.taxajuros:
    image: ${DOCKER_REGISTRY-}softplantaxajuros
    build:
      context: .
      dockerfile: Softplan.TaxaJuros/Dockerfile

  softplan.calculajuros:
    image: ${DOCKER_REGISTRY-}softplancalculajuros
    build:
      context: .
      dockerfile: Softplan.CalculaJuros/Dockerfile

